In [2]:
'''
Practical examples on how to manipulate with numpy array in Python 3.
'''

import numpy as np

dataset = np.array([[0.05, 0.1, 0.01, 0.99], [0.06, 0.12, 0.02, 0.83]])
print("Whole array:\n", dataset)
print("Type of array:", type(dataset))
shape = dataset.shape
print("Shape of array (rows, columns):", shape)
print("Number of rows:", shape[0])
print("Number of columns:", shape[1])

#first two columns:
print("First two columns:")
inputs = dataset[:,:2]
print(inputs)

#remaining columns from 3rd (including):
targets = dataset[:,2:]
print("Last two columns:")
print(targets)

val_1_3 = dataset[1,3]
print("Value in row=1, column=3 (indexing starts with 0):", val_1_3)

Whole array:
 [[ 0.05  0.1   0.01  0.99]
 [ 0.06  0.12  0.02  0.83]]
Type of array: <class 'numpy.ndarray'>
Shape of array (rows, columns): (2, 4)
Number of rows: 2
Number of columns: 4
First two columns:
[[ 0.05  0.1 ]
 [ 0.06  0.12]]
Last two columns:
[[ 0.01  0.99]
 [ 0.02  0.83]]
Value in row=1, column=3 (indexing starts with 0): 0.83
